version: "3"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"

    networks:
      - deploy_network

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

    networks:
      - deploy_network

    depends_on:
      - db


  fastapi:
    container_name: fastapi
    build: backend-fastapi/

    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"


    volumes:
      - ./:/app/fastapi

    networks:
      - deploy_network

    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always


  streamlit:
    container_name: streamlit
    build: frontend-streamlit/

    ports:
      - "8501:8501"

    networks:
      - deploy_network
    
    depends_on:
      - fastapi

    restart: always

volumes:
  backend:
  postgres-db-volume:

  
networks:
  deploy_network:
    driver: bridge